version: '3'
services:

  #PHP Service
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: laravel-image
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./:/var/www/html
    networks:
      - backend

  #Nginx Service
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  #DB Service
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: movies
      MYSQL_ROOT_PASSWORD: rootpasswordmysql
    volumes:
      - mysql-database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-database:
    driver: local
